### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by parrish** [zooniverse/Panoptes-Front-End#1829]
- [ ] Tag search (from #1267) Issue #1834 
- [x] Project association (from #607, #1234, #1042) Issue #1835 
- [x] Fix collaborator editor (from #1027) Issue #1836 
- [x] Add view for collections shared with the user (from #1367) Issue #1837 
- [ ] Fix add subject - validation failed, but adds subject (from #969) Issue #1838 
- [x] Fix collection search (from #969) Issue #1839 
- [ ] Fix name edit autosave (from #881) Issue #1840 
- [x] Fix duplicate collection creation (from #1130).  Issue #1839
- [x] Provide collect-subject button on collection views (from #1652) Issue #1841 
- [ ] Focused talk discussions. Issue #1842, #1843  
- [ ] Mentions.  Issue #1844

**Comment by mschwamb** [comment]
@parrish  So is the plan to leave collections in the current state?

**Comment by mschwamb** [comment]
I think the fact I can't see collections shared with my account  other than be getting a direct link and the not having the ability to favorite or add an image to a collection for subjects in someone else's collection actually are fairly important (I've used that frequently on Planet Four and would have been very helpful during my Planet Four: Terrains searchers).

**Comment by parrish** [comment]
The collection sharing issue is being being worked on.  Until a design pass is done, most of these issues can't be approached.  I'll reopen the summary just for a UX reference though.

**Comment by mschwamb** [comment]
@parrish  I'm not sure how adding more the heart and the link to a bigger image to join the [i] button requires a design pass or 'Tried to create a collection with the same name as one I already had- no error appeared and doesn't add image to collection' ?

**Comment by mschwamb** [comment]
I'm not sure why these can't be kept open in case there is a design pass but I'm sure you have a good reason. Can we reopen  the tickets that don't require any design changes but would make collections function better?

**Comment by srallen** [comment]
@wgranger and @mcbouslog could you each pick one of the issues from items 5-8 on the above list to take a look at? Could you leave a comment here mentioning which one you'll look at and I'll grab one myself.

**Comment by wgranger** [comment]
[1130](https://github.com/zooniverse/Panoptes-Front-End/issues/1130) was a duplicate of [3433](https://github.com/zooniverse/Panoptes-Front-End/issues/3433)

**Comment by srallen** [comment]
Collection search looks fixed, possibly in #2407

**Comment by srallen** [comment]
Closing this as it is old and some of the remaining issues may be resolved. If they aren't, individual issues should be opened with detailed descriptions.
