### ISSUE TITLE
Components that still use PromiseRenderer

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/Panoptes-Front-End#3216]
~~This _doesn't_ include Talk...~~ it totally does

- [x] `app/collections/favorites-button.cjsx`
- [x] `app/collections/collaborators.cjsx`
- [x] `app/collections/settings.cjsx`
- [x] `app/collections/show-list.cjsx`
- [x] `app/collections/show.cjsx`
- [x] `app/components/media-area.cjsx`
- [x] `app/components/promise-renderer.cjsx` (#6243. We'll just delete this once the other components stop using it)
- [x] `app/pages/admin/project-status-list.cjsx`
- [x] `app/pages/admin/project-status.cjsx` (in #3331)
- [x] `app/pages/admin/user-settings.cjsx` (in #3331)
- [x] `app/pages/lab/collaborators.cjsx` (#6233)
- [x] `app/pages/lab/project-details.cjsx` (in #3322)
- [x] `app/pages/lab/project.cjsx` (#6219)
- [x] `app/pages/lab/subject-set.cjsx`
- [x] `app/pages/lab/workflow-viewer/index.cjsx` (James, see (see https://github.com/zooniverse/Panoptes-Front-End/issues/3912))
- [x] `app/pages/lab/workflow.cjsx` (#6228)
- [x] `app/pages/profile/index.cjsx` (in #3342)
- [x] `app/pages/profile/stats.cjsx`
- [x] `app/pages/project/about/education.cjsx`
- [x] `app/pages/project/about/faq.cjsx`
- [x] `app/pages/project/about/index.cjsx`
- [x] `app/pages/project/about/research.cjsx`
- [x] `app/pages/project/about/results.cjsx`
- [x] `app/pages/project/about/team.cjsx`
- [x] `app/pages/settings/email.cjsx`(in #4182)
- [x] `app/pages/settings/profile.cjsx`(in #4142)
- [x] `app/partials/data-export-button.cjsx`
- [x] `app/partials/display-name-slug-editor.cjsx`

**Comment by simoneduca** [comment]
Currently removing it from `app/pages/project/about/team.cjsx`

**Comment by rogerhutchings** [comment]
cc @eatyourgreens @simoneduca 

ref #3215

**Comment by eatyourgreens** [comment]
See #3080 for examples of removing these from the Talk components.

**Comment by eatyourgreens** [comment]
I've made a start on collections this afternoon.

**Comment by eatyourgreens** [comment]
@rogerhutchings the collections pages should all be done now, in #3215 and #3219

**Comment by rogerhutchings** [comment]
I've done the about pages in #3244

**Comment by simoneduca** [comment]
I'll start with `app/partials/data-export-button.cjsx` and then move onto the settings profile and email.

**Comment by eatyourgreens** [comment]
@simoneduca I don't know how similar that is to the Talk data export button, but this might be useful https://github.com/zooniverse/Panoptes-Front-End/pull/3080/commits/65754d723a8307b17a24404fbadd4758f18f0c15

**Comment by simoneduca** [comment]
I'll have a look thanks

**Comment by parrish** [comment]
Going to take a stab at wrapping up the admin components

**Comment by simensta** [comment]
I am working on `app/pages/lab/project-details.cjsx`.

**Comment by srallen** [comment]
As a side of effect at taking a look at what'll be used by the organizations lab, I'm working on a refactor of `app/components/media-area.cjsx`

**Comment by srallen** [comment]
I've started work on `app/pages/lab/project.cjsx`

**Comment by simensta** [comment]
I am working on `app/pages/lab/subject-set.cjsx`

**Comment by eatyourgreens** [comment]
Starting on `app/pages/settings/profile.cjsx`. Hopefully finished later today, as it looks like a fairly small component.
