### ISSUE TITLE
Checklist for Project Builder First Release

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#370]
Wasn't sure where the best place to raise this was, but this seemed like a natural place. As mentioned yesterday, I've got a short list of items (open issues that haven't been marked for finishing by first release) that I'd really like to see when we launch this. @brian-c @chrislintott and anyone else, I'd appreciate thoughts on what's do-able (based on how important they are vs how easy they are).

- [x] Slugifying urls (see #197) - I think this will come up a lot, as all of our projects are likely to have >1 word names
- [x]  Show projects you own *and* collaborate on (see #276)
- [ ]  Change the text for the sub-task button (see #254)
- [ ]  Change "close" to "save" on sub-task popup (or something, see #255, but right now it's confusing)
- [ ]  Adding a "header" text field to display on the landing page (see #371, which I think should keep projects happy but bypass the customization discussion in #295)
- [ ] Add default subject set that users can link to when building a new project (#387)
- [ ] Give drawing tools the option of being required
- [ ] Deploy in-line help text to preview site
- [ ] Show link to preview site from the project builder. Preferably in the left-hand menu section. See issue #253

**Comment by mrniaboc** [comment]
Show link to preview site from the project builder. Preferably in the left-hand menu section. See issue #253

**Comment by mrniaboc** [comment]
In turn there should be an 'edit' button on the preview site for anyone with a role that allows them to edit it. This should disappear once the project is live.

**Comment by brian-c** [comment]
**Please** open an issue and tag it "First release" for things like this.

**Comment by chrissnyder** [comment]
I think a number of these have been done since the issue was posted. Closing as outdated.
