### ISSUE TITLE
workflows request and page_size issue

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#3904]
Notes from Nature now has over 100 workflows (or expeditions). Eventually, NfN will become an organization, with workflows/expeditions spread across many projects, but until then the over 100 workflows need to be listed or accessed in various ways in various components, but [the current default API query limits the `page_size` response to 100](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/lib/get-workflows-in-order.coffee#L6):

- [x] 1. [lab/workflows](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/lab/workflows-container.jsx#L44) - create dynamic paginator in #3908, **but will need revisit if max = 20**
- [x] 2. lab/visibility - add current paginator - Done in #3913 
- [ ] 3. [project/home](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/home/index.jsx#L87) (volunteer selects from all active workflows)
- [x] 4. [project/stats](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/stats/index.jsx#L43) - addressed in #3955, **but will need revisit if max = 20**
- [ ] 5. [admin/project](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/admin/project-status.jsx#L60) - add current paginator(?)
- [ ] 6. [lab/data-exports](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/lab/export-workflows-dialog.jsx#L44) - by workflow, add current paginator(?)

Related
- #2820
- #3144
- #3903

**Comment by srallen** [comment]
@mcbouslog Thanks for opening this. The two most relevant for NfN are probably 1 and 2, so they should be fixed first. For 3, since they have their own landing, I imagine the redirect would send volunteers back to that? I think 3 will need some design input from @beckyrother because a paginator might be awkward, but I don't think listing out 100+ workflows on the page is good UI. 

With the project stats, we probably should fetch the workflows that have been set to be displayed which I think is in the project config. For 5, just normal pagination should work for us and is the lowest priority since we're the only ones to use that.

**Comment by beckyrother** [comment]
I think a paginator would be ok, or if you do list out all 100+ we should add Search and Sort functionality, i.e. sort by date added, name, etc.

**Comment by eatyourgreens** [comment]
There's a pattern we've used elsewhere (the project preferences on the logged-in home page, for example), where the paged query calls itself, on completion, until the total number of results is reached. That would probably work here too.

**Comment by eatyourgreens** [comment]
Something like this:  [query function checks the query metadata](/zooniverse/Panoptes-Front-End/blob/0f01b973e8d22b814bed4afdcebaa1e8382fedaa/app/pages/home-for-user/index.jsx#L155-L158) and calls itself with an incremented page number until the page count is reached.

**Comment by mcbouslog** [comment]
per @camallen on incrementing page calls as needed vs one large call to API:
it really depends on the end point and how much data it has to serialize. If it's a lot then you run into issues with ELB timouts (60s) and serializing data over the network (MBs?).It's a balancing operation, if the api end point is fast and data volumes small then go for it. If it's not the switch to pages of data instead of heavy loading the api and tying up server resources.

Final note, HTTP caching can help with this, it's on my list to cycle back to.

**Comment by mcbouslog** [comment]
6. noted above (lab/data-export by workflow) is an issue the NfN team continues to have. I can create a new issue if prefered, otherwise commenting to remove stale label.

**Comment by mcbouslog** [comment]
See #4370

**Comment by mcbouslog** [comment]
Closing in favor of a specific issue if problem arises, in light of side-loading fix included in #4370.
