### ISSUE TITLE
Remaining style issues for new classifier themes

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#4570]
Taken from the comments from #4470.

- [x] Back button smaller on second step (Penguin Watch, Manatee Chat, Galaxy Zoo), intended? (fixed by #4581)
- [x] dark theme - Done & Talk filled with blue, Back and Done transparent (Penguin Watch), should all these buttons be transparent, then fill on hover? (fixed by #4581)
- [x] dark theme - Back button doesn't have different color fill on hover, just border change, while other buttons have some color fill of button on hover (Penguin Watch) (question in #4584 and closed)
- [x] just Talk button text (not Done & Talk) not on same level as Next button text (Galaxy Builder) (Fixed in #4572)
- [x] "Going back..." warning remains even if not hover on Back button, disappears on hover (Amazo'N'Oil) (Fixed in #4572)
- [x] dark theme, highlighted option before selection hard to see (Galaxy Zoo), in light theme there's light fill of button, in dark theme border just changes subtly, not sure if want some button fill in dark theme too (question in #4584 and closed)
- [x] if no task help, Back and Next/Done very close to task - staging project (Fixed in #4572)
- [x] The Back button isn't disabled on the first task of a workflow, even though it can't be used. It also responds to hover on the first task, and displays the warning message. (Fixed in #4572)
- [x] Back Button: the warning message extends below the box making it harder to read (tested in Firefox 59.0.2). (fixed by #4581)
- [x] Line heights don't match for the task navigation buttons. (Done & Talk) (Fixed on #4572)
- [x] Line 114 in `task-nav.jsx`: I think `this.props.classification.annotations` should be `this.props.annotations` (Fixed in #4572)

From #4572 
- [x] TalkLink: Does it disable them from the keyboard too? If not, consider adding tabindex="-1" when the link is disabled. (fixed by #4581)
- [x] TalkLink: when Done & Talk is disabled, and rendered as a span, it still has cursor: pointer as a style. (fixed by #4581)

Additional ideas:
- [x] Tutorial button should be disabled while it is loading rather than hidden. (fixed by #4599)
- [ ] Double check the disabled button styles for Next and Done with @beckyrother

**Comment by srallen** [comment]
I'm going to close this and open a separate issue about doing an audit of all the button states and styles with @beckyrother
