### ISSUE TITLE
FEM Lab: Nov 2021 misc TODO

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/Panoptes-Front-End#6049]
## Misc ToDo

New behaviour:
- [ ] on FEM-Lab, `workflow.configuration.persist_annotations === undefined` should imply **true**.
  - On PFE-Lab, undefined implies false
  - See zooniverse/front-end-monorepo#2524
- [ ] NEW: on FEM-Lab, `workflow.configuration.hide_classification_summaries ===undefined` should also imply **true**.
- [ ] on FEM-lab, "View Project" and "Test this Workflow" should both point to the FEM preview URL.
  - ~~Note that we want to use `fe-project.zooniverse.org` points to the _production-release_ version of FEM...~~
  - ~~...whereas `frontend.preview.zooniverse.org` points to the _master_ version of FEM, which has not-yet-deployed changes.~~
  - EDIT: use `frontend.preview.zooniverse.org`
- [ ] FEM-Lab should have some visual indicators to separate it from PFE-Lab

**Comment by eatyourgreens** [comment]
NB. preview links to workflows in development will send a 404 response from `fe-project`. At the moment, only active workflows can be previewed in NextJS.

**Comment by shaunanoordin** [comment]
Update from Oxford chat:
- Maybe use `frontend.preview.zooniverse.org` since 1. what Jim said, and 2. @mrniaboc pointed out that most project owners ARE used to the "canary version" of FEM.
- `workflow.configuration. hide_classification_summaries ===undefined` should also imply **true** in FEM-lab

Tagging in Grant as an FYI
