### ISSUE TITLE
Panoptes bird's-eye view

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes-Front-End#78]
- [ ] **Home page**
  To-do. Totally blank at the moment.
  This should highlight some cool projects and Talk discussions.
  When the functionality exists, it will serve as a timeline for signed-in users

- [ ] **Projects listing page**
  Currently lists all projects.
  - [x] Only show "public" projects.
  - [x] Pagination
  - [ ] Filtering (by type, etc.)

- [ ] **Project page** :telescope:
  - [x] Add URL by project owner and name (currently it's by ID).

  - [X] **Landing page**
    Introduction
    Call-to-action link to classify page
    More detailed description. This is Markdown so users can add formatting, partner logos, etc.

  - [X] **Science case page** :telescope:
    - [X] Shows the detailed science case. This is Markdown, so formatting and images are allowed.
    - [ ] Include an auto-generated view of owners and people with roles on the project. #113

  - [ ] **Status page**
    We need to define what data we'll show here and how to generate and access it.

  - [ ] **Results page** :telescope:
    Just a page of free-form text
    
  - [ ] **Classify page** :telescope:
    Currently chooses a random subject from a random workflow.
    - [x] User should be able to choose which workflow they want to do: `/classify/:workflowID`.
    - [ ] Expert users should be able to toggle on "gold standard mode". #116
    - [ ] Expert users should be able to choose their subjects: `/classify/:workflowID/subjectID`.
    - [x] Popup help for each task

    - [X] Creates a classification
      - [X] Single choice task
        - [X] An answer can alter the course of the workflow
      - [X] Multiple choice task
      - [x] Drawing task
        - [x] Each mark can have optional sub-tasks
      - [ ] Camera survey (Serengeti-style)

    - [x] Classification is saved :telescope:
      - [x] Summary is shown :telescope:
        - [x] If subject has "correct" data associated, it will be displayed :telescope:

  - [ ] **Project Talk page** :telescope:
    A list of project talk boards

    - [ ] **Subject details/Talk page** :telescope:
      - [ ] Show subject metadata

- [ ] **Zooniverse-wide talk page**
  Currently on @aweiksnar's plate

- [ ] **User settings page** #58
  Edit your avatar, email address, email settings, etc.

- [ ] **User profiles** #59
  To-do, once we have some kind of timeline feature.
  - [ ] Private messages

- [ ] **Organization profiles**
  To-do, once we have some kind of timeline feature.

- [ ] **Project building landing page**
  - [X] List a user's projects
  - [ ] List projects a user has a role on
  - [ ] "Create a new project" workflow
    A rough prototype is up with basic subject uploading and a JSON field for editing a workflow.
    Currently on @heathv's plate

  - [ ] **Edit project page**
    - [ ] Edit basic details
    - [ ] Edit science case
    - [ ] Add/remove subject sets
      - [ ] Subject set editor
        - [ ] Add/remove a subject from a set
    - [ ] Add/remove workflows
    - [ ] Workflow editing interface
      - [X] Question (single/multiple) editor
        - [X] Define a question
        - [X] Define answers
          - [X] Define next task for single-choice answers
      - [ ] Drawing task editor
        - [X] Define instruction
        - [X] Define shapes
          - [X] Point
          - [X] Line
          - [X] Rectangle
          - [X] Irregular polygon
          - [X] Ellipse
          - [X] Circle
          - [ ] Magnified point (Condors-style)
        - [ ] Define per-mark sub-tasks (simple single- or multiple-choice, displayed all at once)
      - [ ] Camera survey task editor
        Currently on @heathv's plate
    - [ ] Freeze/launch project
    - [ ] Apply for Zooniverse-wide promotion

  - [ ] **Aggregation viewer** (Milkbot) :telescope:

- [x] **Register and sign-in** :telescope:
  - [X] Create/sign in with an email address :telescope:
  - [ ] Create/sign in with a Facebook or Twitter account
  - [X] Modal dialog :telescope:
    Not built, but the forms exist and modal dialog functionality exists. Currently this is a separate page.

- [X] **Reset password page**
  Currently redirects to Zooniverse Home

- [ ] **Privacy policy page**
  To-do, but it's just text. Easy.

- [ ] Site header :telescope:
  - [ ] Main nav
    Link to home, projects list, Zooniverse Talk
  - [X] Sign-in
    Or register
  - [X] Display current user
    Link to settings, project building page

- [ ] Site footer :telescope:
  Privacy, copyright, etc.

**Comment by chrissnyder** [comment]
Looks like most of this is done or otherwise tracked in other issues.
